version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: lab4_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"          # доступ к контейнерной БД с хоста (5434)
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    container_name: lab4_backend
    env_file: .env           # берём остальные переменные из  .env
    environment:
      # DATABASE_URL переопределяем для докер-сети
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/paszi
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: lab4_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
